/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Member;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Account.Account;
import Account.AccountManagement;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public final class MemberDisplayPanel extends javax.swing.JPanel {

    /**
     * Creates new form MemberDisplayPanel
     */
    ArrayList<Member> memberList = MemberManagement.memberList();
    public MemberDisplayPanel() {
        initComponents();
        memberTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        memberTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 24));
        memberTable.getTableHeader().setEnabled(false);
        memberTable.requestFocusInWindow();
        displayMemberTable();
        displayFirstMember();
        SearchTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        memberTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        buttonRefresh = new javax.swing.JButton();
        memberPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        jspInfoPanel = new javax.swing.JScrollPane();
        memberInfoPanel = new javax.swing.JPanel();
        lbIDCardNum = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbDOB = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        lbRegDate = new javax.swing.JLabel();
        lbDisplayEmail = new javax.swing.JLabel();
        lbDisplayAddress = new javax.swing.JLabel();
        btAccount = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        infoEditPanel = new javax.swing.JPanel();
        jspInfoEditPanel = new javax.swing.JScrollPane();
        memberInfoEditPanel = new javax.swing.JPanel();
        lbIDCardNumEdit = new javax.swing.JLabel();
        lbGenderEdit = new javax.swing.JLabel();
        lbDOBEdit = new javax.swing.JLabel();
        lbPhoneEdit = new javax.swing.JLabel();
        lbEmailEdit = new javax.swing.JLabel();
        lbAddressEdit = new javax.swing.JLabel();
        tfIDCardNum = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox<>();
        tfDay = new javax.swing.JTextField();
        tfPhone = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        lbDOBEdit1 = new javax.swing.JLabel();
        tfMonth = new javax.swing.JTextField();
        lbDOBEdit2 = new javax.swing.JLabel();
        tfYear = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        btReturn = new javax.swing.JButton();
        btNewMember = new javax.swing.JButton();

        setBackground(new java.awt.Color(190, 218, 245));

        memberTable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        memberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Library ID", "Full Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        memberTable.setAutoscrolls(false);
        memberTable.setRowHeight(40);
        memberTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        memberTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                memberTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(memberTable);
        if (memberTable.getColumnModel().getColumnCount() > 0) {
            memberTable.getColumnModel().getColumn(0).setResizable(false);
            memberTable.getColumnModel().getColumn(0).setPreferredWidth(150);
            memberTable.getColumnModel().getColumn(1).setResizable(false);
            memberTable.getColumnModel().getColumn(1).setPreferredWidth(500);
        }

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MagnifyingGlass.png"))); // NOI18N

        tfSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfSearch.setForeground(new java.awt.Color(153, 153, 153));
        tfSearch.setText("Search by Library ID/Name");
        tfSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSearchFocusLost(evt);
            }
        });
        tfSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSearchMouseClicked(evt);
            }
        });

        buttonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh.png"))); // NOI18N
        buttonRefresh.setContentAreaFilled(false);
        buttonRefresh.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh_Hover.png"))); // NOI18N
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        memberPanel.setOpaque(false);
        memberPanel.setLayout(new java.awt.CardLayout());

        infoPanel.setOpaque(false);

        jspInfoPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        memberInfoPanel.setBackground(new java.awt.Color(204, 255, 204));
        memberInfoPanel.setPreferredSize(new java.awt.Dimension(550, 350));

        lbIDCardNum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbIDCardNum.setText("ID Card Number: ");

        lbGender.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbGender.setText("Gender: ");

        lbDOB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDOB.setText("D.O.B: ");

        lbPhone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbPhone.setText("Phone: ");

        lbEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbEmail.setText("Email:");

        lbAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbAddress.setText("Address:");

        lbRegDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbRegDate.setText("Registration date: ");

        lbDisplayEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lbDisplayAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout memberInfoPanelLayout = new javax.swing.GroupLayout(memberInfoPanel);
        memberInfoPanel.setLayout(memberInfoPanelLayout);
        memberInfoPanelLayout.setHorizontalGroup(
            memberInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRegDate, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(memberInfoPanelLayout.createSequentialGroup()
                        .addComponent(lbAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDisplayAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbIDCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(memberInfoPanelLayout.createSequentialGroup()
                        .addComponent(lbEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDisplayEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        memberInfoPanelLayout.setVerticalGroup(
            memberInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIDCardNum)
                .addGap(18, 18, 18)
                .addComponent(lbGender)
                .addGap(18, 18, 18)
                .addComponent(lbDOB)
                .addGap(18, 18, 18)
                .addComponent(lbPhone)
                .addGap(18, 18, 18)
                .addGroup(memberInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDisplayEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(memberInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDisplayAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAddress))
                .addGap(18, 18, 18)
                .addComponent(lbRegDate)
                .addGap(89, 89, 89))
        );

        jspInfoPanel.setViewportView(memberInfoPanel);

        btAccount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btAccount.setText("Account");
        btAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAccountMouseExited(evt);
            }
        });
        btAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccountActionPerformed(evt);
            }
        });

        btRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btRemove.setText("Remove");
        btRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRemoveMouseExited(evt);
            }
        });
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        btEdit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btEdit.setText("Edit");
        btEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btEditMouseExited(evt);
            }
        });
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(btEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAccount)))
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEdit)
                    .addComponent(btRemove)
                    .addComponent(btAccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        memberPanel.add(infoPanel, "card2");

        infoEditPanel.setOpaque(false);

        jspInfoEditPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        memberInfoEditPanel.setBackground(new java.awt.Color(204, 255, 204));
        memberInfoEditPanel.setPreferredSize(new java.awt.Dimension(500, 300));

        lbIDCardNumEdit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbIDCardNumEdit.setText("ID Card Number:");

        lbGenderEdit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbGenderEdit.setText("Gender:");

        lbDOBEdit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDOBEdit.setText("D.O.B:");

        lbPhoneEdit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbPhoneEdit.setText("Phone:");

        lbEmailEdit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbEmailEdit.setText("Email:");

        lbAddressEdit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbAddressEdit.setText("Address:");

        tfIDCardNum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfIDCardNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfIDCardNumFocusGained(evt);
            }
        });

        cbGender.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        tfDay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDayFocusGained(evt);
            }
        });

        tfPhone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPhoneFocusGained(evt);
            }
        });

        tfEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailFocusGained(evt);
            }
        });

        jScrollPane2.setPreferredSize(new java.awt.Dimension(450, 100));

        taAddress.setColumns(20);
        taAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taAddress.setLineWrap(true);
        taAddress.setRows(7);
        taAddress.setWrapStyleWord(true);
        taAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                taAddressFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(taAddress);

        lbDOBEdit1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDOBEdit1.setText("-");

        tfMonth.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfMonthFocusGained(evt);
            }
        });

        lbDOBEdit2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDOBEdit2.setText("-");

        tfYear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfYearFocusGained(evt);
            }
        });

        javax.swing.GroupLayout memberInfoEditPanelLayout = new javax.swing.GroupLayout(memberInfoEditPanel);
        memberInfoEditPanel.setLayout(memberInfoEditPanelLayout);
        memberInfoEditPanelLayout.setHorizontalGroup(
            memberInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberInfoEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memberInfoEditPanelLayout.createSequentialGroup()
                        .addComponent(lbAddressEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(memberInfoEditPanelLayout.createSequentialGroup()
                        .addComponent(lbIDCardNumEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIDCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(memberInfoEditPanelLayout.createSequentialGroup()
                        .addComponent(lbGenderEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(memberInfoEditPanelLayout.createSequentialGroup()
                        .addComponent(lbDOBEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDOBEdit1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDOBEdit2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(memberInfoEditPanelLayout.createSequentialGroup()
                        .addComponent(lbPhoneEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(memberInfoEditPanelLayout.createSequentialGroup()
                        .addComponent(lbEmailEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        memberInfoEditPanelLayout.setVerticalGroup(
            memberInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberInfoEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfIDCardNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIDCardNumEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(memberInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbGender)
                    .addComponent(lbGenderEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(memberInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(memberInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbDOBEdit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfYear))
                    .addGroup(memberInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfDay)
                        .addComponent(lbDOBEdit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMonth))
                    .addComponent(lbDOBEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(memberInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPhoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(memberInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(memberInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAddressEdit)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        jspInfoEditPanel.setViewportView(memberInfoEditPanel);

        btSave.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btSave.setText("Save");
        btSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSaveMouseExited(evt);
            }
        });
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btReturn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btReturn.setText("Return");
        btReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btReturnMouseExited(evt);
            }
        });
        btReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoEditPanelLayout = new javax.swing.GroupLayout(infoEditPanel);
        infoEditPanel.setLayout(infoEditPanelLayout);
        infoEditPanelLayout.setHorizontalGroup(
            infoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspInfoEditPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(infoEditPanelLayout.createSequentialGroup()
                        .addComponent(btSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btReturn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        infoEditPanelLayout.setVerticalGroup(
            infoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btReturn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspInfoEditPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );

        memberPanel.add(infoEditPanel, "card3");

        btNewMember.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btNewMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NewMember (Button).png"))); // NOI18N
        btNewMember.setText("NEW MEMBER");
        btNewMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btNewMemberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btNewMemberMouseExited(evt);
            }
        });
        btNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(4, 4, 4)
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(buttonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btNewMember))
                .addGap(18, 18, 18)
                .addComponent(memberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(memberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNewMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void displayMemberTable(){
        DefaultTableModel tableModel = (DefaultTableModel) memberTable.getModel();
        tableModel.setRowCount(0);
        Object[] row = new Object[2];
        for(Member member : memberList){
            row[0] = member.getLibID();
            row[1] = member.getFirstName()+" "+member.getLastName();
            tableModel.addRow(row);
        }
    }
    
    public String displayDate(String date){
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        Date d;
        String str = "";
        try {
            d = dt.parse(date);
            SimpleDateFormat dt1 = new SimpleDateFormat("MMM dd, yyyy");
            str = dt1.format(d);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex, "Alert!", JOptionPane.WARNING_MESSAGE);
        }
        
        return str;
    }
    
    public void displayFirstMember(){
        memberTable.setRowSelectionInterval(0, 0);
        lbIDCardNum.setText("ID Card Number: "+memberList.get(0).getIdCardNumber());
        lbGender.setText("Gender: "+memberList.get(0).getGender());
        lbDOB.setText("D.O.B: "+displayDate(memberList.get(0).getDOB()));
        lbPhone.setText("Phone: "+memberList.get(0).getPhone());
        lbDisplayEmail.setText("<html><p align=\"left\">"+memberList.get(0).getEmail()+"</p></html>");
        lbDisplayAddress.setText("<html><p align=\"left\">"+memberList.get(0).getAddress()+"</p></html>");
        lbRegDate.setText("Registration date: "+displayDate(memberList.get(0).getReg_Date()));
    }
    
    public void displayMemberInfo(){
        int selectedRow = memberTable.getSelectedRow();
        for(Member member : memberList){
            if(String.valueOf(member.getLibID()).equals(memberTable.getModel().getValueAt(selectedRow, 0).toString())){
                lbIDCardNum.setText("ID Card Number: "+member.getIdCardNumber());
                lbGender.setText("Gender: "+member.getGender());
                lbDOB.setText("D.O.B: "+displayDate(member.getDOB()));
                lbPhone.setText("Phone: "+member.getPhone());
                lbDisplayEmail.setText("<html><p align=\"left\">"+member.getEmail()+"</p></html>");
                lbDisplayAddress.setText("<html><p align=\"left\">"+member.getAddress()+"</p></html>");
                lbRegDate.setText("Registration date: "+displayDate(member.getReg_Date()));
                break;
            }
        }
    }
    
    public void displayEditDOB(String date){
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        Date d = null;
        try{
            d = dt.parse(date);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex, "Alert!", JOptionPane.WARNING_MESSAGE);
        }
        if(d!=null){
            tfDay.setText(String.valueOf(d.getDate()));
            tfMonth.setText(String.valueOf(d.getMonth()+1));
            tfYear.setText(String.valueOf(d.getYear()+1900));
        }
    }
    
    public void displayEditMemberInfo(){
        int selectedRow = memberTable.getSelectedRow();
        for(Member member : memberList){
            if(String.valueOf(member.getLibID()).equals(memberTable.getModel().getValueAt(selectedRow, 0).toString())){
                tfIDCardNum.setText(member.getIdCardNumber());
                cbGender.setSelectedItem(member.getGender());
                displayEditDOB(member.getDOB());
                tfPhone.setText(member.getPhone());
                tfEmail.setText(member.getEmail());
                taAddress.setText(member.getAddress());
                break;
            }
        }
    }
    
    public void SearchTable(){        
        DefaultTableModel searchmodel = (DefaultTableModel)memberTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(searchmodel);
        memberTable.setRowSorter(sorter);
        tfSearch.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent de) {
                String text = tfSearch.getText();
                if(text.trim().length()==0 || text.equals("Search by Library ID/Name")){
                    sorter.setRowFilter(null);
                }
                else{
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                String text = tfSearch.getText();
                if(text.trim().length()==0 || text.equals("Search by Library ID/Name")){
                    sorter.setRowFilter(null);
                }
                else{
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                throw new UnsupportedOperationException("Not supported yet."); 
            }
            
    });
    }
    
    private void tfSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSearchFocusGained
        if(tfSearch.getText().equals("Search by Library ID/Name") && tfSearch.isEnabled()){
            tfSearch.setText("");
            tfSearch.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfSearchFocusGained

    private void tfSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSearchFocusLost
        if(tfSearch.getText().isEmpty()){
            tfSearch.setForeground(Color.GRAY);
            tfSearch.setText("Search by Library ID/Name");
        }
    }//GEN-LAST:event_tfSearchFocusLost

    private void tfSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSearchMouseClicked
        if(tfSearch.getText().equals("Search by Library ID/Name") && tfSearch.isEnabled()){
            tfSearch.setText("");
            tfSearch.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfSearchMouseClicked

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        memberList = MemberManagement.memberList();
        displayMemberTable();
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void memberTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberTableMousePressed
        displayMemberInfo();
    }//GEN-LAST:event_memberTableMousePressed
    
    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        int selectedRow = memberTable.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(null, "Please select a member to edit!", "Notification!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(null, "Do you really want to edit this member info?", "Member Editing!", JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
            memberPanel.removeAll();
            memberPanel.add(infoEditPanel);
            memberPanel.revalidate();
            memberPanel.repaint();
            displayEditMemberInfo();
            memberTable.setEnabled(false);
        }
    }//GEN-LAST:event_btEditActionPerformed

    public int checkIDCardNum_IsNumeric(String idCardNum){
        int count = 0;
        for(int i=0;i<idCardNum.length();i++){
            if(!Character.isDigit(idCardNum.charAt(i))){
                count+=1;
            }
        }
        return count;
    }
    
    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to save these changes?", "Confirmation!", JOptionPane.YES_NO_OPTION);
        List<String> errList = new ArrayList();
        if(confirm==JOptionPane.YES_OPTION){
            if(tfIDCardNum.getText().isEmpty()){
                errList.add("ID Card Number");
                tfIDCardNum.setBackground(Color.yellow);
            }
            if(tfEmail.getText().isEmpty()){
                errList.add("Email");
                tfEmail.setBackground(Color.yellow);
            }
            if(tfDay.getText().isEmpty()){
                errList.add("Day");
                tfDay.setBackground(Color.yellow);
            }
            if(tfMonth.getText().isEmpty()){
                errList.add("Month");
                tfMonth.setBackground(Color.yellow);
            }
            if(tfYear.getText().isEmpty()){
                errList.add("Year");
                tfYear.setBackground(Color.yellow);
            }
            if(taAddress.getText().isEmpty()){
                errList.add("Address");
                taAddress.setBackground(Color.yellow);
            }
            if(!errList.isEmpty()){
                String err = "";
                for(String temp : errList){
                    err += temp+"\n";
                }
                JOptionPane.showMessageDialog(null, "The following text field(s) cannot be empty:\n\n"+err, "Information", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            if(tfIDCardNum.getText().length()!=12){
                JOptionPane.showMessageDialog(null, "ID Card Number must have 12 digits in total!", "Information", JOptionPane.INFORMATION_MESSAGE);
                tfIDCardNum.setBackground(Color.yellow);
                return;
            }
            if(checkIDCardNum_IsNumeric(tfIDCardNum.getText())!=0){
                JOptionPane.showMessageDialog(null, "ID Card Number only contains numbers!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfIDCardNum.setBackground(Color.yellow);
                return;
            }
            
            if(!tfPhone.getText().isEmpty()){
                try{
                    Integer.parseInt(tfPhone.getText());
                }catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null, "Phone only contains numbers!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                    tfPhone.setBackground(Color.yellow);
                    return;
                }
            }
            try{
                Integer.parseInt(tfDay.getText());
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Day only contains numbers!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfDay.setBackground(Color.yellow);
                return;
            }
            try{
                Integer.parseInt(tfMonth.getText());
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Month only contains numbers!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfMonth.setBackground(Color.yellow);
                return;
            }
            try{
                Integer.parseInt(tfYear.getText());
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Year only contains numbers!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfYear.setBackground(Color.yellow);
                return;
            }
            
            if(!tfPhone.getText().isEmpty() && tfPhone.getText().length()!=10){
                JOptionPane.showMessageDialog(null, "Phone contains 10 numbers!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfPhone.setBackground(Color.yellow);
                return;
            }

            if(!tfEmail.getText().contains("@")){
                JOptionPane.showMessageDialog(null, "Invalid email!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfEmail.setBackground(Color.yellow);
                return;
            }

            if(Integer.parseInt(tfMonth.getText())>12 || Integer.parseInt(tfMonth.getText())<1){
                JOptionPane.showMessageDialog(null, "Invalid month!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfMonth.setBackground(Color.yellow);
                return;
            }
            
            if(Integer.parseInt(tfDay.getText())<1){
                JOptionPane.showMessageDialog(null, "Invalid day!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfDay.setBackground(Color.yellow);
                return;
            }
            
            if(Integer.parseInt(tfYear.getText())<1){
                JOptionPane.showMessageDialog(null, "Invalid year!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfYear.setBackground(Color.yellow);
                return;
            }
            
            String gender;
            if(cbGender.getSelectedItem().toString().equals("Male"))
                gender = "M";
            else
                gender = "F";

            String DOB = tfYear.getText()+"-"+tfMonth.getText()+"-"+tfDay.getText();
            
            int selectedRow = memberTable.getSelectedRow();
            int libID = Integer.parseInt(memberTable.getValueAt(selectedRow, 0).toString());
            
            MemberManagement.editMember(libID, tfIDCardNum.getText(), gender, DOB, tfPhone.getText(), tfEmail.getText(), taAddress.getText());
            
            memberList = MemberManagement.memberList();
            memberPanel.removeAll();
            memberPanel.add(infoPanel);
            memberPanel.revalidate();
            memberPanel.repaint();
            memberPanel.setEnabled(true);
            displayMemberInfo();
        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void btReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReturnActionPerformed
        memberPanel.removeAll();
        memberPanel.add(infoPanel);
        memberPanel.revalidate();
        memberPanel.repaint();
        displayMemberInfo();
        memberTable.setEnabled(true);
    }//GEN-LAST:event_btReturnActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        int selectedRow = memberTable.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(null, "Please select a member to remove!", "Notification!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int libID = Integer.parseInt(memberTable.getModel().getValueAt(selectedRow, 0).toString());
        String name = memberTable.getModel().getValueAt(selectedRow, 1).toString();
        int confirm = JOptionPane.showConfirmDialog(null, "Do you really want to remove this member?\n\n"+"Library ID: "+libID+"\n"+"Name: "+name, "Confirmation!", JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
            MemberManagement.removeMember(libID);
            
            memberList = MemberManagement.memberList();
            displayMemberTable();
        }
    }//GEN-LAST:event_btRemoveActionPerformed

    private void tfIDCardNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIDCardNumFocusGained
        tfIDCardNum.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfIDCardNumFocusGained

    private void tfDayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDayFocusGained
        tfDay.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfDayFocusGained

    private void tfMonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMonthFocusGained
        tfMonth.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfMonthFocusGained

    private void tfYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfYearFocusGained
        tfYear.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfYearFocusGained

    private void tfPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPhoneFocusGained
        tfPhone.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfPhoneFocusGained

    private void tfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusGained
        tfEmail.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfEmailFocusGained

    private void taAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taAddressFocusGained
        taAddress.setBackground(Color.WHITE);
    }//GEN-LAST:event_taAddressFocusGained

    public void displayAccount(String libID, JLabel lbLibID, JPasswordField pF, JComboBox cbStatus){
        ArrayList<Account> accList = AccountManagement.accountList();
        for(Account acc : accList){
            if(acc.getLibID() == Integer.parseInt(libID)){
                lbLibID.setText(String.valueOf(acc.getLibID()));
                pF.setText(acc.getPassword());
                cbStatus.setSelectedItem(acc.getStatus());
                break;
            }
        }
    }
    
    private void btAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAccountActionPerformed
        int selectedRow = memberTable.getSelectedRow();
        if(selectedRow==-1){
            JOptionPane.showMessageDialog(null, "Please select a member first!", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String libID = memberTable.getModel().getValueAt(selectedRow, 0).toString();
        
        JFrame accFrame = new JFrame("Account");
        accFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        JLabel lbLibID = new JLabel("Library ID:");
        JLabel lbPassword = new JLabel("Password:");
        JLabel lbDisplayLibID = new JLabel(libID);
        JPasswordField pF = new JPasswordField(10);
        JButton btShow = new JButton("Show");
        JLabel lbStatus = new JLabel("Status:");
        JComboBox cbStatus = new JComboBox();
        cbStatus.addItem("Enabled");
        cbStatus.addItem("Disabled");
        
        JButton btSet = new JButton("Set Account");
        JButton btReset = new JButton("Reset");
        
        pF.addFocusListener(new FocusListener(){
            @Override
            public void focusGained(FocusEvent fe) {
                pF.setBackground(Color.WHITE);
            }

            @Override
            public void focusLost(FocusEvent fe) {
                
            }
            
        });
        
        btShow.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                if(pF.getEchoChar()=='*')
                    pF.setEchoChar((char)0);
                else
                    pF.setEchoChar('*');
            }
            
        });
        
        btReset.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                displayAccount(libID, lbDisplayLibID, pF, cbStatus);
            }
            
        });
        
        btSet.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                if(pF.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Password cannot be empty!", "Information", JOptionPane.INFORMATION_MESSAGE);
                    pF.setBackground(Color.yellow);
                    return;
                }
                if(pF.getText().length()<5){
                    JOptionPane.showMessageDialog(null, "Password cannot be less than 5 characters!", "Information", JOptionPane.INFORMATION_MESSAGE);
                    pF.setBackground(Color.yellow);
                    return;
                }
                AccountManagement.setAccount(libID, pF.getText(), cbStatus.getSelectedItem().toString());
                accFrame.dispose();
            }
            
        });
        
        Font font = new Font("Tahoma", Font.PLAIN, 24);
        lbLibID.setFont(font);
        lbPassword.setFont(font);
        lbDisplayLibID.setFont(font);
        pF.setFont(font);
        btShow.setFont(font);
        lbStatus.setFont(font);
        cbStatus.setFont(font);
        
        Font font2 = new Font("Tahoma", Font.BOLD, 24);
        btSet.setFont(font2);
        btReset.setFont(font2);
        
        lbDisplayLibID.setPreferredSize(pF.getPreferredSize());
        lbPassword.setPreferredSize(lbLibID.getPreferredSize());
        lbStatus.setPreferredSize(lbLibID.getPreferredSize());
        
        JPanel accountInfoPanel = new JPanel();
        accountInfoPanel.setPreferredSize(new Dimension(425,190));
        accountInfoPanel.setLayout(new FlowLayout(FlowLayout.LEADING, 15, 20));
        
        
        accountInfoPanel.add(lbLibID);
        accountInfoPanel.add(lbDisplayLibID);
        accountInfoPanel.add(lbPassword);
        accountInfoPanel.add(pF);
        accountInfoPanel.add(btShow);
        accountInfoPanel.add(lbStatus);
        accountInfoPanel.add(cbStatus);
        
        JPanel btPanel = new JPanel();
        btPanel.setPreferredSize(new Dimension(300,50));
        btPanel.add(btSet, BorderLayout.LINE_START);
        btPanel.add(btReset, BorderLayout.LINE_END);
        
        accFrame.add(accountInfoPanel, BorderLayout.NORTH);
        accFrame.add(btPanel, BorderLayout.SOUTH);
        
        accFrame.setSize(480,300);
        accFrame.setLocationRelativeTo(null);
        accFrame.setVisible(true);
        
        displayAccount(libID, lbDisplayLibID, pF, cbStatus);
    }//GEN-LAST:event_btAccountActionPerformed

    private void btNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewMemberActionPerformed
        NewMemberForm nmf = new NewMemberForm();
        nmf.setVisible(true);
    }//GEN-LAST:event_btNewMemberActionPerformed

    private void btSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveMouseEntered
        btSave.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btSaveMouseEntered

    private void btSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveMouseExited
        btSave.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btSaveMouseExited

    private void btReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReturnMouseEntered
        btReturn.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btReturnMouseEntered

    private void btReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReturnMouseExited
        btReturn.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btReturnMouseExited

    private void btNewMemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNewMemberMouseEntered
        btNewMember.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btNewMemberMouseEntered

    private void btNewMemberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNewMemberMouseExited
        btNewMember.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btNewMemberMouseExited

    private void btEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEditMouseEntered
        btEdit.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btEditMouseEntered

    private void btEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEditMouseExited
        btEdit.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btEditMouseExited

    private void btRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoveMouseEntered
        btRemove.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btRemoveMouseEntered

    private void btRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoveMouseExited
        btRemove.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btRemoveMouseExited

    private void btAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAccountMouseEntered
        btAccount.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btAccountMouseEntered

    private void btAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAccountMouseExited
        btAccount.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btAccountMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccount;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btNewMember;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btReturn;
    private javax.swing.JButton btSave;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JPanel infoEditPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jspInfoEditPanel;
    private javax.swing.JScrollPane jspInfoPanel;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbAddressEdit;
    private javax.swing.JLabel lbDOB;
    private javax.swing.JLabel lbDOBEdit;
    private javax.swing.JLabel lbDOBEdit1;
    private javax.swing.JLabel lbDOBEdit2;
    private javax.swing.JLabel lbDisplayAddress;
    private javax.swing.JLabel lbDisplayEmail;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmailEdit;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbGenderEdit;
    private javax.swing.JLabel lbIDCardNum;
    private javax.swing.JLabel lbIDCardNumEdit;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbPhoneEdit;
    private javax.swing.JLabel lbRegDate;
    private javax.swing.JPanel memberInfoEditPanel;
    private javax.swing.JPanel memberInfoPanel;
    private javax.swing.JPanel memberPanel;
    private javax.swing.JTable memberTable;
    private javax.swing.JTextArea taAddress;
    private javax.swing.JTextField tfDay;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfIDCardNum;
    private javax.swing.JTextField tfMonth;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfYear;
    // End of variables declaration//GEN-END:variables
}
