/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package littlelibrary;

import Member.MemberManagement;
import Member.Member;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Admin
 */
public final class LendBookPanel extends javax.swing.JPanel {

    /**
     * Creates new form LendBookPanel
     */
    ArrayList<Book> bookList = BookManagement.bookList();
    ArrayList<Member> memberList = MemberManagement.memberList();
    public LendBookPanel() {
        initComponents();
        displayDueDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspMemberInfoPanel = new javax.swing.JScrollPane();
        memberInfoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbIDCardNum = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbDOB = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbRegDate = new javax.swing.JLabel();
        lbFullName = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfLibID = new javax.swing.JTextField();
        btSearchMember = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfISBN = new javax.swing.JTextField();
        btSearchBook = new javax.swing.JButton();
        bookPanel = new javax.swing.JPanel();
        lbISBN = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        lbCover = new javax.swing.JLabel();
        btLend = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfDay = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbDueDate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(190, 218, 245));

        jspMemberInfoPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspMemberInfoPanel.setPreferredSize(new java.awt.Dimension(590, 390));

        memberInfoPanel.setBackground(new java.awt.Color(204, 255, 204));
        memberInfoPanel.setPreferredSize(new java.awt.Dimension(588, 470));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Full Name:");

        lbIDCardNum.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbIDCardNum.setText("ID Card Num:");

        lbGender.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbGender.setText("Gender:");

        lbDOB.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbDOB.setText("D.O.B:");

        lbPhone.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbPhone.setText("Phone:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setText("Address:");

        lbRegDate.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbRegDate.setText("Registration Date:");

        lbFullName.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N

        lbEmail.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N

        lbAddress.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N

        javax.swing.GroupLayout memberInfoPanelLayout = new javax.swing.GroupLayout(memberInfoPanel);
        memberInfoPanel.setLayout(memberInfoPanelLayout);
        memberInfoPanelLayout.setHorizontalGroup(
            memberInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRegDate, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIDCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(memberInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(memberInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(memberInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        memberInfoPanelLayout.setVerticalGroup(
            memberInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lbFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lbIDCardNum)
                .addGap(18, 18, 18)
                .addComponent(lbGender)
                .addGap(18, 18, 18)
                .addComponent(lbDOB)
                .addGap(18, 18, 18)
                .addComponent(lbPhone)
                .addGap(18, 18, 18)
                .addGroup(memberInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(memberInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lbAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lbRegDate)
                .addGap(107, 107, 107))
        );

        jspMemberInfoPanel.setViewportView(memberInfoPanel);

        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-Member ID-");

        tfLibID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfLibID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfLibIDFocusGained(evt);
            }
        });

        btSearchMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MagnifyingGlass.png"))); // NOI18N
        btSearchMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSearchMemberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSearchMemberMouseExited(evt);
            }
        });
        btSearchMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btSearchMember, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(tfLibID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLibID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSearchMember)
                .addContainerGap())
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel3.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("-ISBN-");

        tfISBN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfISBN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfISBNFocusGained(evt);
            }
        });

        btSearchBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MagnifyingGlass.png"))); // NOI18N
        btSearchBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSearchBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSearchBookMouseExited(evt);
            }
        });
        btSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSearchBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSearchBook)
                .addContainerGap())
        );

        bookPanel.setBackground(new java.awt.Color(197, 235, 223));
        bookPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lbISBN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbISBN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbISBN.setText("ISBN");

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Title");

        lbCover.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lbCover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout bookPanelLayout = new javax.swing.GroupLayout(bookPanel);
        bookPanel.setLayout(bookPanelLayout);
        bookPanelLayout.setHorizontalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbCover, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        bookPanelLayout.setVerticalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbISBN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbCover, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        btLend.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btLend.setText("LEND");
        btLend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLendMouseExited(evt);
            }
        });
        btLend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLendActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("For:");

        tfDay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfDay.setText("?");
        tfDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDayFocusGained(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("days");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Due Date:");

        lbDueDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbDueDate.setForeground(new java.awt.Color(255, 51, 0));
        lbDueDate.setText("?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspMemberInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfDay))
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGap(31, 31, 31)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btLend, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbDueDate))
                .addGap(18, 18, 18)
                .addComponent(bookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btLend, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfDay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDueDate)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jspMemberInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String displayDate(String date){
        if(date.isEmpty())
            return "-";
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdf2 = new SimpleDateFormat("MMM dd, yyyy");
        Date d;
        String str = "";
        try {
            d = sdf.parse(date);
            str = sdf2.format(d);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex, "Alert!", JOptionPane.WARNING_MESSAGE);
        }
        
        return str;
    }
    
    public void displayMemberInfo(){
        int count=0;
        for(Member member : memberList){
            if(member.getLibID() == Integer.parseInt(tfLibID.getText())){
                lbFullName.setText("<html><p align=\"left\" width=\"410\">"+member.getFirstName()+" "+member.getLastName()+"</p></html>");
                lbIDCardNum.setText("ID Card Number: "+member.getIdCardNumber());
                lbGender.setText("Gender: "+member.getGender());
                lbDOB.setText("D.O.B: "+displayDate(member.getDOB()));
                lbPhone.setText("Phone: "+member.getPhone());
                lbEmail.setText("<html><p align=\"left\" width=\"465\">"+member.getEmail()+"</p></html>");
                lbAddress.setText("<html><p align=\"left\" width=\"435\">"+member.getAddress()+"</p></html>");
                lbRegDate.setText("Registration Date: "+member.getReg_Date());
                count+=1;
                break;
            }
        }
        if(count==0)
            JOptionPane.showMessageDialog(null, "Member not found!", "Information", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public int checkISBN_IsNumeric(String ISBN){
        int count = 0;
        for(int i=0;i<ISBN.length();i++){
            if(Character.isDigit(ISBN.charAt(i))){
                count+=1;
            }
        }
        return count;
    }
    
    public void checkTitleLength(JLabel lbTitle, String title){
        UIManager.put("ToolTip.font", new Font("Tahoma", Font.BOLD, 18));
        if(lbTitle.getToolTipText()!=null)
            lbTitle.setToolTipText(null);
        
        if(title.length()>39){
            lbTitle.setText("<html><p align=\"center\" width=\"265\">"+title.substring(0, 39)+"..."+"</p></html>");
            lbTitle.setToolTipText("<html><p align=\"center\" width=\"290\">"+title+"</p></html>");
        }
        else
            lbTitle.setText("<html><p align=\"center\" width=\"265\">"+title+"</p></html>");
    }
    
    public ImageIcon resizedImage_SmallerSize(byte[] b){
        ImageIcon icon = new ImageIcon(b);
        Image image = icon.getImage().getScaledInstance(200, 250, Image.SCALE_DEFAULT);
        ImageIcon resizedIcon = new ImageIcon(image);
        return resizedIcon;
    }
    
    public void setCover_SmallerSize(JLabel lbCover, int index){
        if(bookList.get(index).getImage()!=null){
            ImageIcon cover = resizedImage_SmallerSize(bookList.get(index).getImage());
            lbCover.setIcon(cover);
        }
        else{
            ImageIcon cover = new ImageIcon(System.getProperty("user.dir")+"/src/BookCover/Empty.jpg");
            Image image = cover.getImage().getScaledInstance(200, 250, Image.SCALE_DEFAULT);
            ImageIcon resizedIcon = new ImageIcon(image);
            lbCover.setIcon(resizedIcon);
        }
    }
    
    public void displayBookInfo(){
        int count = 0;
        for(int i=0; i<bookList.size(); i++){
            if(bookList.get(i).getISBN().equals(tfISBN.getText())){
                lbISBN.setText(bookList.get(i).getISBN());
                checkTitleLength(lbTitle, bookList.get(i).getTitle());
                setCover_SmallerSize(lbCover, i);
                count+=1;
                break;
            }
        }
        if(count==0)
            JOptionPane.showMessageDialog(null, "Book not found!", "Information", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public int checkDayInput(){
        if(tfDay.getText().isEmpty()){
            lbDueDate.setText("?");
            return 1;
        }
        try{
            Integer.parseInt(tfDay.getText());
        }catch(NumberFormatException e){
            lbDueDate.setText("?");
            return 1;
        }
        if(Integer.parseInt(tfDay.getText())<1){
            lbDueDate.setText("?");
            return 1;
        }
        return 0;
    }
    
    public void formatDueDate(){
        if(checkDayInput()==0){
            SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy HH:mm:ss");
            Calendar cal = Calendar.getInstance();
            cal.add(Calendar.DATE, Integer.parseInt(tfDay.getText()));
            Date date = cal.getTime();
            lbDueDate.setText(sdf.format(date));
        }
    }
    
    public void displayDueDate(){
        tfDay.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent de) {
                formatDueDate();
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                formatDueDate();
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                
            }
            
        });
    }
    
    public int checkLibIDInput(){
        if(tfLibID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter the library ID!", "Information", JOptionPane.INFORMATION_MESSAGE);
            tfLibID.setBackground(Color.yellow);
            return 1;
        }
        
        if(tfLibID.getText().length()!=9){
            JOptionPane.showMessageDialog(null, "Library ID contains 9 digits in total!", "Information", JOptionPane.INFORMATION_MESSAGE);
            tfLibID.setBackground(Color.yellow);
            return 1;
        }
        
        try{
            Integer.parseInt(tfLibID.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Library ID only contains numbers!", "Information",JOptionPane.INFORMATION_MESSAGE);
            tfLibID.setBackground(Color.yellow);
            return 1;
        }
        
        return 0;
    }
    
    public int checkISBNInput(){
        if(tfISBN.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter the international standard book number!", "Information", JOptionPane.INFORMATION_MESSAGE);
            tfISBN.setBackground(Color.yellow);
            return 1;
        }
        if(tfISBN.getText().length()!=13){
            JOptionPane.showMessageDialog(null, "ISBN contains 13 digits in total!", "Information", JOptionPane.INFORMATION_MESSAGE);
            tfISBN.setBackground(Color.yellow);
            return 1;
        }
        if(checkISBN_IsNumeric(tfISBN.getText())!=13){
            JOptionPane.showMessageDialog(null, "ISBN only contains numbers!", "Information", JOptionPane.INFORMATION_MESSAGE);
            tfISBN.setBackground(Color.yellow);
            return 1;
        }
        
        return 0;
    }
    
    private void tfLibIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLibIDFocusGained
        tfLibID.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfLibIDFocusGained

    private void tfISBNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfISBNFocusGained
        tfISBN.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfISBNFocusGained

    private void btSearchMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchMemberActionPerformed
        if(checkLibIDInput()==0)
            displayMemberInfo();
    }//GEN-LAST:event_btSearchMemberActionPerformed

    private void btSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchBookActionPerformed
        if(checkISBNInput()==0)
            displayBookInfo();
    }//GEN-LAST:event_btSearchBookActionPerformed

    private void tfDayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDayFocusGained
        if(tfDay.getText().equals("?"))
            tfDay.setText("");
        tfDay.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfDayFocusGained

    private void btLendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLendActionPerformed
        if(checkLibIDInput()==0 && checkISBNInput()==0 && checkDayInput()==0){
            
            if(Integer.parseInt(tfDay.getText())>14){
                JOptionPane.showMessageDialog(null, "Cannot lend for more than 14 days!", "Information", JOptionPane.INFORMATION_MESSAGE);
                tfDay.setText("?");
                lbDueDate.setText("?");
                return;
            }
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            SimpleDateFormat sdf2 = new SimpleDateFormat("MMM dd, yyyy HH:mm:ss");
            
            Date date;
            try {
                date = sdf2.parse(lbDueDate.getText());
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, ex, "Alert!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            Calendar cal = Calendar.getInstance();
            
            String dueDate = sdf.format(date);
            String curDate = sdf.format(cal.getTime());
            
            float bookPrice = 0;
            for(Book book : bookList){
                if(book.getISBN().equals(tfISBN.getText())){
                    bookPrice = book.getPrice();
                    break;
                }
            }
            
            
            float deposit = bookPrice*25/100;
            
            BorrowInfoManagement.addBorrowedBook(tfISBN.getText(), Integer.parseInt(tfLibID.getText()), curDate , dueDate, deposit);
            
            JOptionPane.showMessageDialog(null, "Lending successful!\n\n"+"ISBN: "+tfISBN.getText()+"\n"+"Member ID: "+tfLibID.getText()+"\n"+"For: "+tfDay.getText()+" days"
                    , "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btLendActionPerformed

    private void btLendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLendMouseEntered
        btLend.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btLendMouseEntered

    private void btLendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLendMouseExited
        btLend.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btLendMouseExited

    private void btSearchMemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchMemberMouseEntered
        btSearchMember.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btSearchMemberMouseEntered

    private void btSearchMemberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchMemberMouseExited
        btSearchMember.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btSearchMemberMouseExited

    private void btSearchBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchBookMouseEntered
        btSearchBook.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btSearchBookMouseEntered

    private void btSearchBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchBookMouseExited
        btSearchBook.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btSearchBookMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookPanel;
    private javax.swing.JButton btLend;
    private javax.swing.JButton btSearchBook;
    private javax.swing.JButton btSearchMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane jspMemberInfoPanel;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbCover;
    private javax.swing.JLabel lbDOB;
    private javax.swing.JLabel lbDueDate;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbIDCardNum;
    private javax.swing.JLabel lbISBN;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbRegDate;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel memberInfoPanel;
    private javax.swing.JTextField tfDay;
    private javax.swing.JTextField tfISBN;
    private javax.swing.JTextField tfLibID;
    // End of variables declaration//GEN-END:variables
}
