/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Staff;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Account.Account;
import Account.AccountManagement;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public final class StaffDisplayPanel extends javax.swing.JPanel {

    /**
     * Creates new form StaffDisplayPanel
     */
    ArrayList<Staff> staffList = StaffManagement.staffList();
    public StaffDisplayPanel() {
        initComponents();
        staffTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        staffTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 24));
        staffTable.getTableHeader().setEnabled(false);
        staffTable.requestFocusInWindow();
        displayStaffTable();
        displayFirstStaff();
        SearchTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        btRefresh = new javax.swing.JButton();
        staffPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        jspInfoPanel = new javax.swing.JScrollPane();
        staffInfoPanel = new javax.swing.JPanel();
        lbPosition = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbDOB = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        lbStartDate = new javax.swing.JLabel();
        lbDisplayEmail = new javax.swing.JLabel();
        lbDisplayAddress = new javax.swing.JLabel();
        btEdit = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        btAccount = new javax.swing.JButton();
        infoEditPanel = new javax.swing.JPanel();
        jspInfoEditPanel = new javax.swing.JScrollPane();
        staffInfoEditPanel = new javax.swing.JPanel();
        lbPosition1 = new javax.swing.JLabel();
        lbGender1 = new javax.swing.JLabel();
        lbDOB1 = new javax.swing.JLabel();
        lbPhone1 = new javax.swing.JLabel();
        lbEmail1 = new javax.swing.JLabel();
        lbAddress1 = new javax.swing.JLabel();
        cbPosition = new javax.swing.JComboBox<>();
        cbGender = new javax.swing.JComboBox<>();
        tfDay = new javax.swing.JTextField();
        lbDOB2 = new javax.swing.JLabel();
        tfMonth = new javax.swing.JTextField();
        lbDOB3 = new javax.swing.JLabel();
        tfYear = new javax.swing.JTextField();
        tfPhone = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        btSave = new javax.swing.JButton();
        btReturn = new javax.swing.JButton();
        btNewStaff = new javax.swing.JButton();

        setBackground(new java.awt.Color(190, 218, 245));

        staffTable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Library ID", "Full Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        staffTable.setAutoscrolls(false);
        staffTable.setRowHeight(40);
        staffTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        staffTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(staffTable);
        if (staffTable.getColumnModel().getColumnCount() > 0) {
            staffTable.getColumnModel().getColumn(0).setResizable(false);
            staffTable.getColumnModel().getColumn(0).setPreferredWidth(150);
            staffTable.getColumnModel().getColumn(1).setResizable(false);
            staffTable.getColumnModel().getColumn(1).setPreferredWidth(500);
        }

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MagnifyingGlass.png"))); // NOI18N

        tfSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfSearch.setForeground(new java.awt.Color(153, 153, 153));
        tfSearch.setText("Search by Library ID/Name");
        tfSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSearchFocusLost(evt);
            }
        });
        tfSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSearchMouseClicked(evt);
            }
        });

        btRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh.png"))); // NOI18N
        btRefresh.setContentAreaFilled(false);
        btRefresh.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh_Hover.png"))); // NOI18N
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        staffPanel.setOpaque(false);
        staffPanel.setLayout(new java.awt.CardLayout());

        infoPanel.setOpaque(false);

        jspInfoPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        staffInfoPanel.setBackground(new java.awt.Color(204, 255, 204));
        staffInfoPanel.setPreferredSize(new java.awt.Dimension(550, 350));

        lbPosition.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbPosition.setText("Position: ");

        lbGender.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbGender.setText("Gender: ");

        lbDOB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDOB.setText("D.O.B: ");

        lbPhone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbPhone.setText("Phone: ");

        lbEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbEmail.setText("Email:");

        lbAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbAddress.setText("Address:");

        lbStartDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbStartDate.setText("Start date: ");

        lbDisplayEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lbDisplayAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout staffInfoPanelLayout = new javax.swing.GroupLayout(staffInfoPanel);
        staffInfoPanel.setLayout(staffInfoPanelLayout);
        staffInfoPanelLayout.setHorizontalGroup(
            staffInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(staffInfoPanelLayout.createSequentialGroup()
                        .addComponent(lbAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDisplayAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(staffInfoPanelLayout.createSequentialGroup()
                        .addComponent(lbEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDisplayEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        staffInfoPanelLayout.setVerticalGroup(
            staffInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPosition)
                .addGap(18, 18, 18)
                .addComponent(lbGender)
                .addGap(18, 18, 18)
                .addComponent(lbDOB)
                .addGap(18, 18, 18)
                .addComponent(lbPhone)
                .addGap(18, 18, 18)
                .addGroup(staffInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEmail)
                    .addComponent(lbDisplayEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(staffInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAddress)
                    .addComponent(lbDisplayAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lbStartDate)
                .addGap(89, 89, 89))
        );

        jspInfoPanel.setViewportView(staffInfoPanel);

        btEdit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btEdit.setText("Edit");
        btEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btEditMouseExited(evt);
            }
        });
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btRemove.setText("Remove");
        btRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRemoveMouseExited(evt);
            }
        });
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        btAccount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btAccount.setText("Account");
        btAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAccountMouseExited(evt);
            }
        });
        btAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspInfoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(btEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAccount)))
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEdit)
                    .addComponent(btRemove)
                    .addComponent(btAccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        staffPanel.add(infoPanel, "card2");

        infoEditPanel.setOpaque(false);

        jspInfoEditPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        staffInfoEditPanel.setBackground(new java.awt.Color(204, 255, 204));
        staffInfoEditPanel.setPreferredSize(new java.awt.Dimension(500, 300));

        lbPosition1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbPosition1.setText("Position:");

        lbGender1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbGender1.setText("Gender:");

        lbDOB1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDOB1.setText("D.O.B:");

        lbPhone1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbPhone1.setText("Phone:");

        lbEmail1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbEmail1.setText("Email:");

        lbAddress1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbAddress1.setText("Address:");

        cbPosition.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Librarian", "Technician", "Assistant" }));

        cbGender.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        tfDay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDayFocusGained(evt);
            }
        });

        lbDOB2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDOB2.setText("-");

        tfMonth.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfMonthFocusGained(evt);
            }
        });

        lbDOB3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDOB3.setText("-");

        tfYear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfYearFocusGained(evt);
            }
        });

        tfPhone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPhoneFocusGained(evt);
            }
        });

        tfEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailFocusGained(evt);
            }
        });

        jScrollPane2.setPreferredSize(new java.awt.Dimension(450, 100));

        taAddress.setColumns(20);
        taAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taAddress.setLineWrap(true);
        taAddress.setRows(7);
        taAddress.setWrapStyleWord(true);
        taAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                taAddressFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(taAddress);

        javax.swing.GroupLayout staffInfoEditPanelLayout = new javax.swing.GroupLayout(staffInfoEditPanel);
        staffInfoEditPanel.setLayout(staffInfoEditPanelLayout);
        staffInfoEditPanelLayout.setHorizontalGroup(
            staffInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffInfoEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffInfoEditPanelLayout.createSequentialGroup()
                        .addComponent(lbAddress1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staffInfoEditPanelLayout.createSequentialGroup()
                        .addComponent(lbPosition1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staffInfoEditPanelLayout.createSequentialGroup()
                        .addComponent(lbGender1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staffInfoEditPanelLayout.createSequentialGroup()
                        .addComponent(lbDOB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDOB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDOB3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staffInfoEditPanelLayout.createSequentialGroup()
                        .addComponent(lbPhone1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staffInfoEditPanelLayout.createSequentialGroup()
                        .addComponent(lbEmail1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        staffInfoEditPanelLayout.setVerticalGroup(
            staffInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffInfoEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbPosition)
                    .addComponent(lbPosition1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(staffInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbGender)
                    .addComponent(lbGender1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(staffInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(staffInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfDay)
                        .addComponent(lbDOB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMonth)
                        .addComponent(lbDOB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfYear))
                    .addComponent(lbDOB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(staffInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffInfoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAddress1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        jspInfoEditPanel.setViewportView(staffInfoEditPanel);

        btSave.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btSave.setText("Save");
        btSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSaveMouseExited(evt);
            }
        });
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btReturn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btReturn.setText("Return");
        btReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btReturnMouseExited(evt);
            }
        });
        btReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoEditPanelLayout = new javax.swing.GroupLayout(infoEditPanel);
        infoEditPanel.setLayout(infoEditPanelLayout);
        infoEditPanelLayout.setHorizontalGroup(
            infoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspInfoEditPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoEditPanelLayout.createSequentialGroup()
                        .addComponent(btSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btReturn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        infoEditPanelLayout.setVerticalGroup(
            infoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btReturn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspInfoEditPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );

        staffPanel.add(infoEditPanel, "card3");

        btNewStaff.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btNewStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NewStaff (Button).png"))); // NOI18N
        btNewStaff.setText("NEW STAFF");
        btNewStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btNewStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btNewStaffMouseExited(evt);
            }
        });
        btNewStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(4, 4, 4)
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(btRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btNewStaff))
                .addGap(18, 18, 18)
                .addComponent(staffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(staffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNewStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void displayStaffTable(){
        DefaultTableModel tableModel = (DefaultTableModel) staffTable.getModel();
        tableModel.setRowCount(0);
        Object[] row = new Object[2];
        for(Staff staff : staffList){
            row[0] = staff.getLibID();
            row[1] = staff.getFirstName()+" "+staff.getLastName();
            tableModel.addRow(row);
        }
    }
    
    public String displayDate(String date){
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        Date d;
        String str = "";
        try {
            d = dt.parse(date);
            SimpleDateFormat dt1 = new SimpleDateFormat("MMM dd, yyyy");
            str = dt1.format(d);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex, "Alert!", JOptionPane.WARNING_MESSAGE);
        }
        
        return str;
    }
    
    public void displayFirstStaff(){
        staffTable.setRowSelectionInterval(0, 0);
        lbPosition.setText("ID Card Number: "+staffList.get(0).getPosition());
        lbGender.setText("Gender: "+staffList.get(0).getGender());
        lbDOB.setText("D.O.B: "+displayDate(staffList.get(0).getDOB()));
        lbPhone.setText("Phone: "+staffList.get(0).getPhone());
        lbDisplayEmail.setText("<html><p align=\"left\">"+staffList.get(0).getEmail()+"</p></html>");
        lbDisplayAddress.setText("<html><p align=\"left\">"+staffList.get(0).getAddress()+"</p></html>");
        lbStartDate.setText("Registration date: "+displayDate(staffList.get(0).getStart_Date()));
    }
    
    public void displayStaffInfo(){
        int selectedRow = staffTable.getSelectedRow();
        for(Staff staff : staffList){
            if(String.valueOf(staff.getLibID()).equals(staffTable.getModel().getValueAt(selectedRow, 0).toString())){
                lbPosition.setText("Position: "+staff.getPosition());
                lbGender.setText("Gender: "+staff.getGender());
                lbDOB.setText("D.O.B: "+displayDate(staff.getDOB()));
                lbPhone.setText("Phone: "+staff.getPhone());
                lbDisplayEmail.setText("<html><p align=\"left\">"+staff.getEmail()+"</p></html>");
                lbDisplayAddress.setText("<html><p align=\"left\">"+staff.getAddress()+"</p></html>");
                lbStartDate.setText("Start date: "+displayDate(staff.getStart_Date()));
                break;
            }
        }
    }
    
    public void displayEditDOB(String date){
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        Date d = null;
        try{
            d = dt.parse(date);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex, "Alert!", JOptionPane.WARNING_MESSAGE);
        }
        if(d!=null){
            tfDay.setText(String.valueOf(d.getDate()));
            tfMonth.setText(String.valueOf(d.getMonth()+1));
            tfYear.setText(String.valueOf(d.getYear()+1900));
        }
    }
    
    public void displayEditStaffInfo(){
        int selectedRow = staffTable.getSelectedRow();
        for(Staff staff : staffList){
            if(String.valueOf(staff.getLibID()).equals(staffTable.getModel().getValueAt(selectedRow, 0).toString())){
                cbPosition.setSelectedItem(staff.getPosition());
                cbGender.setSelectedItem(staff.getGender());
                displayEditDOB(staff.getDOB());
                tfPhone.setText(staff.getPhone());
                tfEmail.setText(staff.getEmail());
                taAddress.setText(staff.getAddress());
                break;
            }
        }
    }
    
    public void hideButton(){
        btNewStaff.setVisible(false);
        btEdit.setVisible(false);
        btRemove.setVisible(false);
        btAccount.setVisible(false);
    }
    
    public void SearchTable(){        
        DefaultTableModel searchmodel = (DefaultTableModel)staffTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(searchmodel);
        staffTable.setRowSorter(sorter);
        tfSearch.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent de) {
                String text = tfSearch.getText();
                if(text.trim().length()==0 || text.equals("Search by Library ID/Name")){
                    sorter.setRowFilter(null);
                }
                else{
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                String text = tfSearch.getText();
                if(text.trim().length()==0 || text.equals("Search by Library ID/Name")){
                    sorter.setRowFilter(null);
                }
                else{
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                throw new UnsupportedOperationException("Not supported yet."); 
            }
            
    });
    }
    
    private void staffTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffTableMousePressed
        displayStaffInfo();
    }//GEN-LAST:event_staffTableMousePressed

    private void tfSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSearchFocusGained
        if(tfSearch.getText().equals("Search by Library ID/Name") && tfSearch.isEnabled()){
            tfSearch.setText("");
            tfSearch.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfSearchFocusGained

    private void tfSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSearchFocusLost
        if(tfSearch.getText().isEmpty()){
            tfSearch.setForeground(Color.GRAY);
            tfSearch.setText("Search by Library ID/Name");
        }
    }//GEN-LAST:event_tfSearchFocusLost

    private void tfSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSearchMouseClicked
        if(tfSearch.getText().equals("Search by Library ID/Name") && tfSearch.isEnabled()){
            tfSearch.setText("");
            tfSearch.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfSearchMouseClicked

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        staffList = StaffManagement.staffList();
        displayStaffTable();
    }//GEN-LAST:event_btRefreshActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        int selectedRow = staffTable.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(null, "Please select a staff to edit!", "Notification!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null, "Do you really want to edit this staff info?", "Member Editing!", JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
            staffPanel.removeAll();
            staffPanel.add(infoEditPanel);
            staffPanel.revalidate();
            staffPanel.repaint();
            displayEditStaffInfo();
            staffTable.setEnabled(false);
        }
    }//GEN-LAST:event_btEditActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        int selectedRow = staffTable.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(null, "Please select a staff to remove!", "Notification!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int libID = Integer.parseInt(staffTable.getModel().getValueAt(selectedRow, 0).toString());
        String name = staffTable.getModel().getValueAt(selectedRow, 1).toString();
        int confirm = JOptionPane.showConfirmDialog(null, "Do you really want to remove this staff?\n\n"+"Library ID: "+libID+"\n"+"Name: "+name, "Confirmation!", JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
            StaffManagement.removeStaff(libID);
            
            staffList = StaffManagement.staffList();
            displayStaffTable();
        }
    }//GEN-LAST:event_btRemoveActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to save these changes?", "Confirmation!", JOptionPane.YES_NO_OPTION);
        List<String> errList = new ArrayList();
        if(confirm==JOptionPane.YES_OPTION){
            if(tfEmail.getText().isEmpty()){
                errList.add("Email");
                tfEmail.setBackground(Color.yellow);
            }
            if(tfPhone.getText().isEmpty()){
                errList.add("Phone");
                tfPhone.setBackground(Color.yellow);
            }
            if(tfDay.getText().isEmpty()){
                errList.add("Day");
                tfDay.setBackground(Color.yellow);
            }
            if(tfMonth.getText().isEmpty()){
                errList.add("Month");
                tfMonth.setBackground(Color.yellow);
            }
            if(tfYear.getText().isEmpty()){
                errList.add("Year");
                tfYear.setBackground(Color.yellow);
            }
            if(taAddress.getText().isEmpty()){
                errList.add("Address");
                taAddress.setBackground(Color.yellow);
            }
            if(!errList.isEmpty()){
                String err = "";
                for(String temp : errList){
                    err += temp+"\n";
                }
                JOptionPane.showMessageDialog(null, "The following text field(s) cannot be empty:\n\n"+err, "Information", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            if(!tfPhone.getText().isEmpty()){
                try{
                    Integer.parseInt(tfPhone.getText());
                }catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null, "Phone only contains numbers!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                    tfPhone.setBackground(Color.yellow);
                    return;
                }
            }
            try{
                Integer.parseInt(tfDay.getText());
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Day only contains numbers!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfDay.setBackground(Color.yellow);
                return;
            }
            try{
                Integer.parseInt(tfMonth.getText());
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Month only contains numbers!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfMonth.setBackground(Color.yellow);
                return;
            }
            try{
                Integer.parseInt(tfYear.getText());
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Year only contains numbers!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfYear.setBackground(Color.yellow);
                return;
            }
            
            if(!tfPhone.getText().isEmpty() && tfPhone.getText().length()!=10){
                JOptionPane.showMessageDialog(null, "Phone contains 10 numbers!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfPhone.setBackground(Color.yellow);
                return;
            }

            if(!tfEmail.getText().contains("@")){
                JOptionPane.showMessageDialog(null, "Invalid email!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfEmail.setBackground(Color.yellow);
                return;
            }

            if(Integer.parseInt(tfMonth.getText())>12 || Integer.parseInt(tfMonth.getText())<1){
                JOptionPane.showMessageDialog(null, "Invalid month!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfMonth.setBackground(Color.yellow);
                return;
            }
            
            if(Integer.parseInt(tfDay.getText())<1){
                JOptionPane.showMessageDialog(null, "Invalid day!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfDay.setBackground(Color.yellow);
                return;
            }
            
            if(Integer.parseInt(tfYear.getText())<1){
                JOptionPane.showMessageDialog(null, "Invalid year!", "Alert!", JOptionPane.INFORMATION_MESSAGE);
                tfYear.setBackground(Color.yellow);
                return;
            }
            
            String gender;
            if(cbGender.getSelectedItem().toString().equals("Male"))
                gender = "M";
            else
                gender = "F";

            String DOB = tfYear.getText()+"-"+tfMonth.getText()+"-"+tfDay.getText();
            
            int selectedRow = staffTable.getSelectedRow();
            int libID = Integer.parseInt(staffTable.getValueAt(selectedRow, 0).toString());
            
            StaffManagement.editStaff(libID, cbPosition.getSelectedItem().toString(), gender, DOB, tfPhone.getText(), tfEmail.getText(), taAddress.getText());
            
            staffList = StaffManagement.staffList();
            staffPanel.removeAll();
            staffPanel.add(infoPanel);
            staffPanel.revalidate();
            staffPanel.repaint();
            displayStaffInfo();
            staffTable.setEnabled(true);
        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void btReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReturnActionPerformed
        staffPanel.removeAll();
        staffPanel.add(infoPanel);
        staffPanel.revalidate();
        staffPanel.repaint();
        displayStaffInfo();
        staffTable.setEnabled(true);
    }//GEN-LAST:event_btReturnActionPerformed

    private void tfDayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDayFocusGained
        tfDay.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfDayFocusGained

    private void tfMonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMonthFocusGained
        tfMonth.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfMonthFocusGained

    private void tfYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfYearFocusGained
        tfYear.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfYearFocusGained

    private void tfPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPhoneFocusGained
        tfPhone.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfPhoneFocusGained

    private void tfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusGained
        tfEmail.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfEmailFocusGained

    private void taAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taAddressFocusGained
        taAddress.setBackground(Color.WHITE);
    }//GEN-LAST:event_taAddressFocusGained

    public void displayAccount(String libID, JLabel lbLibID, JPasswordField pF, JComboBox cbStatus){
        ArrayList<Account> accList = AccountManagement.accountList();
        for(Account acc : accList){
            if(acc.getLibID() == Integer.parseInt(libID)){
                lbLibID.setText(String.valueOf(acc.getLibID()));
                pF.setText(acc.getPassword());
                cbStatus.setSelectedItem(acc.getStatus());
                break;
            }
        }
    }
    
    private void btAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAccountActionPerformed
        int selectedRow = staffTable.getSelectedRow();
        if(selectedRow==-1){
            JOptionPane.showMessageDialog(null, "Please select a staff first!", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String libID = staffTable.getModel().getValueAt(selectedRow, 0).toString();
        
        JFrame accFrame = new JFrame("Account");
        accFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        JLabel lbLibID = new JLabel("Library ID:");
        JLabel lbPassword = new JLabel("Password:");
        JLabel lbDisplayLibID = new JLabel(libID);
        JPasswordField pF = new JPasswordField(10);
        JButton btShow = new JButton("Show");
        JLabel lbStatus = new JLabel("Status:");
        JComboBox cbStatus = new JComboBox();
        cbStatus.addItem("Enabled");
        cbStatus.addItem("Disabled");
        
        JButton btSet = new JButton("Set Account");
        JButton btReset = new JButton("Reset");
        
        pF.addFocusListener(new FocusListener(){
            @Override
            public void focusGained(FocusEvent fe) {
                pF.setBackground(Color.WHITE);
            }

            @Override
            public void focusLost(FocusEvent fe) {
                
            }
            
        });
        
        btShow.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                if(pF.getEchoChar()=='*')
                    pF.setEchoChar((char)0);
                else
                    pF.setEchoChar('*');
            }
            
        });
        
        btReset.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                displayAccount(libID, lbDisplayLibID, pF, cbStatus);
            }
            
        });
        
        btSet.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                if(pF.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Password cannot be empty!", "Information", JOptionPane.INFORMATION_MESSAGE);
                    pF.setBackground(Color.yellow);
                    return;
                }
                if(pF.getText().length()<5){
                    JOptionPane.showMessageDialog(null, "Password cannot be less than 5 characters!", "Information", JOptionPane.INFORMATION_MESSAGE);
                    pF.setBackground(Color.yellow);
                    return;
                }
                AccountManagement.setAccount(libID, pF.getText(), cbStatus.getSelectedItem().toString());
                accFrame.dispose();
            }
            
        });
        
        Font font = new Font("Tahoma", Font.PLAIN, 24);
        lbLibID.setFont(font);
        lbPassword.setFont(font);
        lbDisplayLibID.setFont(font);
        pF.setFont(font);
        btShow.setFont(font);
        lbStatus.setFont(font);
        cbStatus.setFont(font);
        
        Font font2 = new Font("Tahoma", Font.BOLD, 24);
        btSet.setFont(font2);
        btReset.setFont(font2);
        
        lbDisplayLibID.setPreferredSize(pF.getPreferredSize());
        lbPassword.setPreferredSize(lbLibID.getPreferredSize());
        lbStatus.setPreferredSize(lbLibID.getPreferredSize());
        
        JPanel accountInfoPanel = new JPanel();
        accountInfoPanel.setPreferredSize(new Dimension(425,190));
        accountInfoPanel.setLayout(new FlowLayout(FlowLayout.LEADING, 15, 20));
        
        accountInfoPanel.add(lbLibID);
        accountInfoPanel.add(lbDisplayLibID);
        accountInfoPanel.add(lbPassword);
        accountInfoPanel.add(pF);
        accountInfoPanel.add(btShow);
        accountInfoPanel.add(lbStatus);
        accountInfoPanel.add(cbStatus);
        
        JPanel btPanel = new JPanel();
        btPanel.setPreferredSize(new Dimension(300,50));
        btPanel.add(btSet, BorderLayout.LINE_START);
        btPanel.add(btReset, BorderLayout.LINE_END);
        
        accFrame.add(accountInfoPanel, BorderLayout.NORTH);
        accFrame.add(btPanel, BorderLayout.SOUTH);
        
        accFrame.setSize(480,300);
        accFrame.setLocationRelativeTo(null);
        accFrame.setVisible(true);
        
        displayAccount(libID, lbDisplayLibID, pF, cbStatus);
    }//GEN-LAST:event_btAccountActionPerformed

    private void btNewStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewStaffActionPerformed
        NewStaffForm nsf = new NewStaffForm();
        nsf.setVisible(true);
    }//GEN-LAST:event_btNewStaffActionPerformed

    private void btNewStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNewStaffMouseEntered
        btNewStaff.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btNewStaffMouseEntered

    private void btNewStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNewStaffMouseExited
        btNewStaff.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btNewStaffMouseExited

    private void btEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEditMouseEntered
        btEdit.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btEditMouseEntered

    private void btEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEditMouseExited
        btEdit.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btEditMouseExited

    private void btRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoveMouseEntered
        btRemove.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btRemoveMouseEntered

    private void btRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoveMouseExited
        btRemove.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btRemoveMouseExited

    private void btAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAccountMouseEntered
        btAccount.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btAccountMouseEntered

    private void btAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAccountMouseExited
        btAccount.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btAccountMouseExited

    private void btSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveMouseEntered
        btSave.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btSaveMouseEntered

    private void btSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveMouseExited
        btSave.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btSaveMouseExited

    private void btReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReturnMouseEntered
        btReturn.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btReturnMouseEntered

    private void btReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReturnMouseExited
        btReturn.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btReturnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccount;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btNewStaff;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btReturn;
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbPosition;
    private javax.swing.JPanel infoEditPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jspInfoEditPanel;
    private javax.swing.JScrollPane jspInfoPanel;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbAddress1;
    private javax.swing.JLabel lbDOB;
    private javax.swing.JLabel lbDOB1;
    private javax.swing.JLabel lbDOB2;
    private javax.swing.JLabel lbDOB3;
    private javax.swing.JLabel lbDisplayAddress;
    private javax.swing.JLabel lbDisplayEmail;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmail1;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbGender1;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbPhone1;
    private javax.swing.JLabel lbPosition;
    private javax.swing.JLabel lbPosition1;
    private javax.swing.JLabel lbStartDate;
    private javax.swing.JPanel staffInfoEditPanel;
    private javax.swing.JPanel staffInfoPanel;
    private javax.swing.JPanel staffPanel;
    private javax.swing.JTable staffTable;
    private javax.swing.JTextArea taAddress;
    private javax.swing.JTextField tfDay;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfMonth;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfYear;
    // End of variables declaration//GEN-END:variables
}
