/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/**
 *
 * @author Admin
 */
public final class EmailSendingForm extends javax.swing.JFrame {

    /**
     * Creates new form EmailSendingForm
     */
    String attachment = "";
    public EmailSendingForm() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(190,218,245));
        lbWelcome.setText("<html><p align=\"left\">"+"Welcome, 18dthqa2projectphucnguyen@gmail.com"+"</p></html>");
        btRemove.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbWelcome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMessage = new javax.swing.JTextArea();
        tfSubject = new javax.swing.JTextField();
        tfTo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btAttachment = new javax.swing.JButton();
        lbAttachment = new javax.swing.JLabel();
        btRemove = new javax.swing.JButton();
        lbAttachmentName = new javax.swing.JLabel();
        btSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Email Sending");

        lbWelcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbWelcome.setForeground(new java.awt.Color(0, 102, 102));
        lbWelcome.setText("Welcome, (email address)");

        jPanel1.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Subject:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("To:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Message:");

        taMessage.setColumns(20);
        taMessage.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taMessage.setLineWrap(true);
        taMessage.setRows(5);
        taMessage.setWrapStyleWord(true);
        taMessage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                taMessageFocusGained(evt);
            }
        });
        taMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taMessageKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(taMessage);

        tfSubject.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfSubject.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfSubjectFocusGained(evt);
            }
        });
        tfSubject.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSubjectKeyPressed(evt);
            }
        });

        tfTo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfTo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfToFocusGained(evt);
            }
        });
        tfTo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfToKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTo, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTo)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfSubject)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(590, 150));

        btAttachment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btAttachment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Attachment.png"))); // NOI18N
        btAttachment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAttachmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAttachmentMouseExited(evt);
            }
        });
        btAttachment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAttachmentActionPerformed(evt);
            }
        });

        lbAttachment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbAttachment.setText("Attachment:");

        btRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/X Mark (2).png"))); // NOI18N
        btRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRemoveMouseExited(evt);
            }
        });
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        lbAttachmentName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbAttachmentName.setText("?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbAttachment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAttachmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btAttachment, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRemove)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAttachment)
                    .addComponent(lbAttachmentName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAttachment)
                    .addComponent(btRemove))
                .addContainerGap())
        );

        btSend.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btSend.setText("SEND");
        btSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSendMouseExited(evt);
            }
        });
        btSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(btSend, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbWelcome)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSend, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Session getSession(){
        String username = "18dthqa2projectphucnguyen@gmail.com";
        String password = "projectphucnguyen123";
        String host = "smtp.gmail.com";
        int port = 587;
        Properties pt = new Properties();
        pt.put("mail.smtp.host", host);
        pt.put("mail.smtp.port", port);
        pt.put("mail.smtp.auth", "true");
        pt.put("mail.smtp.starttls.enable", "true");
        Session ss = Session.getInstance(pt, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });
        return ss;
    }
    
    public void getAttachedFile(){
        JFileChooser fc = new JFileChooser();
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
            lbAttachmentName.setText(f.getName());
            attachment = f.getPath();
            btRemove.setVisible(true);
        }
    }
    
    public void sendEmail(){
        String from = "18dthqa2projectphucnguyen@gmail.com";
        String to = tfTo.getText();
        String message = taMessage.getText();
        String subject = tfSubject.getText();
        
        if(to.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter the email address to send!", "Information", JOptionPane.INFORMATION_MESSAGE);
            tfTo.setBackground(Color.yellow);
            return;
        }
        
        if(message.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter the message!", "Information", JOptionPane.INFORMATION_MESSAGE);
            taMessage.setBackground(Color.yellow);
            return;
        }
        
        if(subject.isEmpty()){
            JOptionPane.showMessageDialog(null, "Subject cannot be empty!", "Information", JOptionPane.INFORMATION_MESSAGE);
            tfSubject.setBackground(Color.yellow);
            return;
        }
        
        Session ss = getSession();
        
        try {
            MimeMessage msg = new MimeMessage(ss);
            try {
                msg.setFrom(new InternetAddress(from, "Library MS Project"));
            } catch (UnsupportedEncodingException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            msg.setSubject(subject);
            msg.setRecipient(Message.RecipientType.TO, new InternetAddress(to));
            
            MimeMultipart multipart = new MimeMultipart();
            MimeBodyPart msgbody = new MimeBodyPart();
            msgbody.setText(message);
            multipart.addBodyPart(msgbody);
            MimeBodyPart attachmentbody = new MimeBodyPart();
            
            if(!attachment.isEmpty()){
                File attachedFile = new File(attachment);
                if(attachedFile.exists()){
                    try {
                        attachmentbody.attachFile(attachedFile);
                        multipart.addBodyPart(attachmentbody);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, ex, "Alert!", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
            msg.setContent(multipart);
            Transport.send(msg);
            JOptionPane.showMessageDialog(null, "Sending Email Successful!");
        } catch (MessagingException ex) {
            JOptionPane.showMessageDialog(null, ex, "Alert!", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void btSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSendActionPerformed
        sendEmail();
    }//GEN-LAST:event_btSendActionPerformed

    private void tfToFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfToFocusGained
        tfTo.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfToFocusGained

    private void tfSubjectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSubjectFocusGained
        tfSubject.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfSubjectFocusGained

    private void taMessageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taMessageFocusGained
        taMessage.setBackground(Color.WHITE);
    }//GEN-LAST:event_taMessageFocusGained

    private void btAttachmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAttachmentActionPerformed
        getAttachedFile();
    }//GEN-LAST:event_btAttachmentActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        attachment = "";
        lbAttachmentName.setText("?");
        btRemove.setVisible(false);
    }//GEN-LAST:event_btRemoveActionPerformed

    private void tfToKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfToKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btSend.doClick();
        }
    }//GEN-LAST:event_tfToKeyPressed

    private void tfSubjectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSubjectKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btSend.doClick();
        }
    }//GEN-LAST:event_tfSubjectKeyPressed

    private void taMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taMessageKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btSend.doClick();
        }
    }//GEN-LAST:event_taMessageKeyPressed

    private void btSendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSendMouseEntered
        btSend.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btSendMouseEntered

    private void btSendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSendMouseExited
        btSend.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btSendMouseExited

    private void btAttachmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAttachmentMouseEntered
        btAttachment.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btAttachmentMouseEntered

    private void btAttachmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAttachmentMouseExited
        btAttachment.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btAttachmentMouseExited

    private void btRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoveMouseEntered
        btRemove.setBackground(new Color(120,165,208));
    }//GEN-LAST:event_btRemoveMouseEntered

    private void btRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoveMouseExited
        btRemove.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_btRemoveMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAttachment;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btSend;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAttachment;
    private javax.swing.JLabel lbAttachmentName;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JTextArea taMessage;
    private javax.swing.JTextField tfSubject;
    private javax.swing.JTextField tfTo;
    // End of variables declaration//GEN-END:variables
}
